MONGODB_HOST: mongodb-{{ env }}.akhiladevops.fun # mongodb-dev.akhiladevops.fun
REDIS_HOST: redis-{{ env }}.akhiladevops.fun
CATALOGUE_HOST: catalogue-{{ env }}.akhiladevops.fun
CART_HOST: cart-{{ env }}.akhiladevops.fun
USER_HOST: user-{{ env }}.akhiladevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.akhiladevops.fun
MYSQL_HOST: mysql-{{ env }}.akhiladevops.fun
SHIPPING_HOST: shipping-{{ env }}.akhiladevops.fun
PAYMENT_HOST: payment-{{ env }}.akhiladevops.fun